--INSERT INTO DRAMA (NAME, EPISODES, ACTOR, GENRE) VALUES ('The Walking Dead', 16,  'Andrew Lincoln', 'Horror' );
--INSERT INTO MOVIE (NAME, ACTOR, GENRE, RATING) VALUES ('Minions', 'Sandra Bullock', 'Animation', 6.5);
--INSERT INTO COFFEE (NAME, LOCAL, PRICE, TESTING) VALUES ('first', 'U.S', 200, 'yes');
--INSERT INTO Notebook (BRAND, NAME, CPU, PRICE) VALUES ('ASUS', 'ZenBook-UX305FA', 'Intel Core M 5Y10 處理器', 40000);

--INSERT INTO GAME (NAME, EVALUATION, DOWNLOAD, URL) VALUES ('部落衝突', 5, 3000000, 'www.coc.com.tw')
--INSERT INTO GAME (NAME, EVALUATION, DOWNLOAD, URL) VALUES ('皇室戰爭', 4, 1000000, 'www.cor.com.tw')
--INSERT INTO GAME (NAME, EVALUATION, DOWNLOAD, URL) VALUES ('神魔之塔', 5, 4000000, 'www.tos.com.tw')
--INSERT INTO GAME (NAME, EVALUATION, DOWNLOAD, URL) VALUES ('爐石戰記', 4, 6000000, 'www.heartstone.com.tw')
--INSERT INTO GAME (NAME, EVALUATION, DOWNLOAD, URL) VALUES ('列王的紛爭', 3, 2000000, 'www.cok.com.tw')

INSERT INTO BRAND (BRANDNAME, BRANDCNAME, BRANDIMG, WEBSITE, BCFUNC, BRANDSHOW) VALUES ('Biore', '蜜妮', 'src\main\webapp\WEB-INF\img\brand\Biore.png', 'http://www.kao.com/tw/biore/' , 'biore',1)
INSERT INTO BRAND (BRANDNAME, BRANDCNAME, BRANDIMG, WEBSITE, BCFUNC, BRANDSHOW) VALUES ('Clinique', '倩碧', 'src\main\webapp\WEB-INF\img\brand\Clinique.png', 'http://www.clinique.com.tw/' , 'elca',1)
INSERT INTO BRAND (BRANDNAME, BRANDCNAME, BRANDIMG, WEBSITE, BCFUNC, BRANDSHOW) VALUES ('M.A.C', '', 'src\main\webapp\WEB-INF\img\brand\M.A.C.png', 'https://www.maccosmetics.com.tw/' , 'elca',1)
INSERT INTO BRAND (BRANDNAME, BRANDCNAME, BRANDIMG, WEBSITE, BCFUNC, BRANDSHOW) VALUES ('Lancome', '蘭蔻', 'src\main\webapp\WEB-INF\img\brand\Lancome.png', 'http://www.lancome.com.tw/lancome/_zh/_tw/index.aspx' , 'loreal',1)
INSERT INTO BRAND (BRANDNAME, BRANDCNAME, BRANDIMG, WEBSITE, BCFUNC, BRANDSHOW) VALUES ('L''Oreal', '巴黎萊雅', 'src\main\webapp\WEB-INF\img\brand\L''Oreal.png', 'http://www.loreal.com.tw/' , 'loreal',1)

INSERT INTO CATEGORYTITLE (TITLENAME) VALUES ('臉部保養')
INSERT INTO CATEGORYTITLE (TITLENAME) VALUES ('化妝產品')

INSERT INTO Category (CATEGORYNAME, CATEGORYIMG, TITLEID) VALUES ('lotion','src/...', 1)
INSERT INTO Category (CATEGORYNAME, CATEGORYIMG, TITLEID) VALUES ('cream','src/...', 1)
INSERT INTO Category (CATEGORYNAME, CATEGORYIMG, TITLEID) VALUES ('facial mask','src/...', 1)
INSERT INTO Category (CATEGORYNAME, CATEGORYIMG, TITLEID) VALUES ('foundation','src/...', 2)
INSERT INTO Category (CATEGORYNAME, CATEGORYIMG, TITLEID) VALUES ('sun protection','src/...', 2)

INSERT INTO REVIEW (MEMBERID, PRODID, REVIEWTITLE, REVIEW, REVIEWRATING, REVIEWIMG, REVIEWTIME, REWCOLLECT, REVIEWSHOW) VALUES (1000, 10, '心得標題1', '內文1', '5', 'src\main\webapp\WEB-INF\img\review\心得標題1.png', '2016-06-19', '99', 1)
INSERT INTO REVIEW (MEMBERID, PRODID, REVIEWTITLE, REVIEW, REVIEWRATING, REVIEWIMG, REVIEWTIME, REWCOLLECT, REVIEWSHOW) VALUES (2000, 20, '心得標題2', '內文2', '4', 'src\main\webapp\WEB-INF\img\review\心得標題2.png', '2016-06-19', '88', 0)
INSERT INTO REVIEW (MEMBERID, PRODID, REVIEWTITLE, REVIEW, REVIEWRATING, REVIEWIMG, REVIEWTIME, REWCOLLECT, REVIEWSHOW) VALUES (3000, 30, '心得標題3', '內文3', '3', 'src\main\webapp\WEB-INF\img\review\心得標題3.png', '2016-06-26', '77', 1)
INSERT INTO REVIEW (MEMBERID, PRODID, REVIEWTITLE, REVIEW, REVIEWRATING, REVIEWIMG, REVIEWTIME, REWCOLLECT, REVIEWSHOW) VALUES (4000, 40, '心得標題4', '內文4', '3', 'src\main\webapp\WEB-INF\img\review\心得標題4.png', '2016-06-26', '66', 0)
INSERT INTO REVIEW (MEMBERID, PRODID, REVIEWTITLE, REVIEW, REVIEWRATING, REVIEWIMG, REVIEWTIME, REWCOLLECT, REVIEWSHOW) VALUES (5000, 50, '心得標題5', '內文5', '4', 'src\main\webapp\WEB-INF\img\review\心得標題5.png', '2016-06-26', '55', 1)
INSERT INTO REVIEW (MEMBERID, PRODID, REVIEWTITLE, REVIEW, REVIEWRATING, REVIEWIMG, REVIEWTIME, REWCOLLECT, REVIEWSHOW) VALUES (6000, 60, '心得標題6', '內文6', '5', 'src\main\webapp\WEB-INF\img\review\心得標題6.png', '2016-06-26', '44', 0)

INSERT INTO REVIEWCM (REVIEWID, REVIEWCMMSG, MEMBERID, REVIEWCMSHOW, REVIEWCMREPORT) VALUES (100, '內容1', 10, 1, 99)
INSERT INTO REVIEWCM (REVIEWID, REVIEWCMMSG, MEMBERID, REVIEWCMSHOW, REVIEWCMREPORT) VALUES (200, '內容2', 20, 0, 88)

INSERT INTO ARTICLECM (ARTICLEID, ARTICLECMMSG, MEMBERID, ARTICLECMSHOW, ARTICLECMREPORT) VALUES (99, '內容1', 11, 1, 11)
INSERT INTO ARTICLECM (ARTICLEID, ARTICLECMMSG, MEMBERID, ARTICLECMSHOW, ARTICLECMREPORT) VALUES (88, '內容2', 22, 0, 22)
INSERT INTO ARTICLECM (ARTICLEID, ARTICLECMMSG, MEMBERID, ARTICLECMSHOW, ARTICLECMREPORT) VALUES (77, '內容3', 33, 1, 33)

INSERT INTO Ingredient (INGREDName, INGREDCHName, INGREDChar, INGREDIrritant, INGREDAcne, INGREDSafety) values ('Water', '水', '溶劑', 0, 0, 1)
INSERT INTO Ingredient (INGREDName, INGREDCHName, INGREDChar, INGREDIrritant, INGREDAcne, INGREDSafety) values ('Titanium Dioxide', '二氧化鈦', '防曬', 0, 0, 2)
INSERT INTO Ingredient (INGREDName, INGREDCHName, INGREDChar, INGREDIrritant, INGREDAcne, INGREDSafety) values ('Carbomer', '卡波莫, 卡波姆, 聚羧乙烯, 卡波樹脂', '黏度控制,乳化劑', 0, 1, 1)
INSERT INTO Ingredient (INGREDName, INGREDCHName, INGREDChar, INGREDIrritant, INGREDAcne, INGREDSafety) values ('Cyclomethicone', '矽靈, 環聚二甲基矽氧烷, 環甲矽脂, 環甲基矽氧烷', '溶劑,黏度控制,抗靜電,保溼,柔潤劑', 0, 0, 2)
INSERT INTO Ingredient (INGREDName, INGREDCHName, INGREDChar, INGREDIrritant, INGREDAcne, INGREDSafety) values ('Natto gum', '納托膠',null, 0, 0, 1)
INSERT INTO Ingredient (INGREDName, INGREDCHName, INGREDChar, INGREDIrritant, INGREDAcne, INGREDSafety) values ('Glycyrrhiza Glabra Root Extract','光果甘草根萃取', '香料,鎮靜消炎,柔潤劑', 0, 0, 1)
INSERT INTO Ingredient (INGREDName, INGREDCHName, INGREDChar, INGREDIrritant, INGREDAcne, INGREDSafety) values ('Dimethicone','矽靈,地美司康,二甲基矽酮,二甲矽油,聚二甲基矽氧烷', '柔潤劑', 1, 0, 1)


INSERT INTO PRODUCT (PRODNAME, BRANDID, CATEGORYID, WEIGHT, SCORE, PRICE, CAPACITY, LAUNCHDATE, PRODDESC, MAINIGDT, CONCENTRATION, PRODIMG) VALUES ('產品1', 1, 1, 1.0, 1.5, 150, 100, '2016-06-12', '產品說明1', 1, 0.3, 'src\main\webapp\WEB-INF\img\product\產品1.png')
INSERT INTO PRODUCT (PRODNAME, BRANDID, CATEGORYID, WEIGHT, SCORE, PRICE, CAPACITY, LAUNCHDATE, PRODDESC, MAINIGDT, CONCENTRATION, PRODIMG) VALUES ('產品1', 2, 2, 2.0, 2.5, 250, 200, '2016-06-12', '產品說明2', 2, 0.2, 'src\main\webapp\WEB-INF\img\product\產品2.png')
INSERT INTO PRODUCT (PRODNAME, BRANDID, CATEGORYID, WEIGHT, SCORE, PRICE, CAPACITY, LAUNCHDATE, PRODDESC, MAINIGDT, CONCENTRATION, PRODIMG) VALUES ('產品3', 3, 3, 3.0, 3.5, 350, 300, '2016-06-12', '產品說明3', 3, 0.6, 'src\main\webapp\WEB-INF\img\product\產品3.png')
INSERT INTO PRODUCT (PRODNAME, BRANDID, CATEGORYID, WEIGHT, SCORE, PRICE, CAPACITY, LAUNCHDATE, PRODDESC, MAINIGDT, CONCENTRATION, PRODIMG) VALUES ('產品4', 1, 1, 4.0, 4.5, 450, 400, '2016-06-12', '產品說明4', 1, 0.9, 'src\main\webapp\WEB-INF\img\product\產品4.png')
INSERT INTO PRODUCT (PRODNAME, BRANDID, CATEGORYID, WEIGHT, SCORE, PRICE, CAPACITY, LAUNCHDATE, PRODDESC, MAINIGDT, CONCENTRATION, PRODIMG) VALUES ('產品5', 3, 3, 3.0, 3.5, 350, 300, '2016-06-12', '產品說明5', 2, 0.5, 'src\main\webapp\WEB-INF\img\product\產品5.png')
INSERT INTO PRODUCT (PRODNAME, BRANDID, CATEGORYID, WEIGHT, SCORE, PRICE, CAPACITY, LAUNCHDATE, PRODDESC, MAINIGDT, CONCENTRATION, PRODIMG) VALUES ('產品6', 2, 2, 2.0, 2.5, 250, 200, '2016-06-12', '產品說明6', 3, 0.7, 'src\main\webapp\WEB-INF\img\product\產品6.png')
INSERT INTO PRODUCT (PRODNAME, BRANDID, CATEGORYID, WEIGHT, SCORE, PRICE, CAPACITY, LAUNCHDATE, PRODDESC, MAINIGDT, CONCENTRATION, PRODIMG) VALUES ('產品7', 1, 1, 1.0, 1.5, 150, 100, '2016-06-12', '產品說明7', 1, 1.0, 'src\main\webapp\WEB-INF\img\product\產品7.png')
INSERT INTO PRODUCT (PRODNAME, BRANDID, CATEGORYID, WEIGHT, SCORE, PRICE, CAPACITY, LAUNCHDATE, PRODDESC, MAINIGDT, CONCENTRATION, PRODIMG) VALUES ('產品8', 1, 1, 1.0, 1.5, 150, 100, '2016-06-12', '產品說明8', 2, 0.5, 'src\main\webapp\WEB-INF\img\product\產品8.png')
INSERT INTO PRODUCT (PRODNAME, BRANDID, CATEGORYID, WEIGHT, SCORE, PRICE, CAPACITY, LAUNCHDATE, PRODDESC, MAINIGDT, CONCENTRATION, PRODIMG) VALUES ('產品9', 2, 2, 2.0, 2.5, 250, 200, '2016-06-12', '產品說明9', 3, 0.2, 'src\main\webapp\WEB-INF\img\product\產品9.png')
INSERT INTO PRODUCT (PRODNAME, BRANDID, CATEGORYID, WEIGHT, SCORE, PRICE, CAPACITY, LAUNCHDATE, PRODDESC, MAINIGDT, CONCENTRATION, PRODIMG) VALUES ('產品10', 3, 3, 3.0, 3.5, 350, 300, '2016-06-12', '產品說明10', 1, 0.4, 'src\main\webapp\WEB-INF\img\product\產品10.png')
INSERT INTO PRODUCT (PRODNAME, BRANDID, CATEGORYID, WEIGHT, SCORE, PRICE, CAPACITY, LAUNCHDATE, PRODDESC, MAINIGDT, CONCENTRATION, PRODIMG) VALUES ('產品11', 1, 1, 4.0, 4.5, 450, 400, '2016-06-12', '產品說明11', 2, 1.0, 'src\main\webapp\WEB-INF\img\product\產品11.png')
INSERT INTO PRODUCT (PRODNAME, BRANDID, CATEGORYID, WEIGHT, SCORE, PRICE, CAPACITY, LAUNCHDATE, PRODDESC, MAINIGDT, CONCENTRATION, PRODIMG) VALUES ('產品12', 3, 3, 3.0, 3.5, 350, 300, '2016-06-12', '產品說明12', 3, 0.3, 'src\main\webapp\WEB-INF\img\product\產品12.png')
INSERT INTO PRODUCT (PRODNAME, BRANDID, CATEGORYID, WEIGHT, SCORE, PRICE, CAPACITY, LAUNCHDATE, PRODDESC, MAINIGDT, CONCENTRATION, PRODIMG) VALUES ('產品13', 2, 2, 2.0, 2.5, 250, 200, '2016-06-12', '產品說明13', 2, 0.2, 'src\main\webapp\WEB-INF\img\product\產品13.png')
INSERT INTO PRODUCT (PRODNAME, BRANDID, CATEGORYID, WEIGHT, SCORE, PRICE, CAPACITY, LAUNCHDATE, PRODDESC, MAINIGDT, CONCENTRATION, PRODIMG) VALUES ('產品14', 1, 1, 1.0, 1.5, 150, 100, '2016-06-12', '產品說明14', 1, 0.1, 'src\main\webapp\WEB-INF\img\product\產品14.png')

INSERT INTO EXPDATE(MEMBERID,BRANDID,PROID,BATCHCODE,MFD,EXP) values (1,1,1,333,'2008-01-16','2011-01-16')
INSERT INTO EXPDATE(memberId,brandId,proId,batchCode,mfd,exp) values (1,2,2,555,'2008-01-16','2011-01-16')
INSERT INTO EXPDATE(memberId,brandId,proId,batchCode,mfd,exp) values (2,9,9,999,'2008-01-16','2011-01-16')

INSERT INTO MEMBER(EMAIL, PASSWORD, NICKNAME, LASTNAME, FIRSTNAME, GENDER, BIRTHDAY, SKINTYPE, MEMBERIMG, PHONE, ADDR, MEMBERSUSPEND, MEMBERSUSPENDDAYS) VALUES ('jenny@gmail.com', 'abc1234', 'little J', 'Wang', 'Jenny', 'F', '1988-01-01', 'sensitive', 'src\main\webapp\WEB-INF\img\member\member_default.png', '0910123456', 'Taipei Taiwan', 0, '30')
INSERT INTO MEMBER(EMAIL, PASSWORD, NICKNAME, LASTNAME, FIRSTNAME, GENDER, BIRTHDAY, SKINTYPE, MEMBERIMG, PHONE, ADDR, MEMBERSUSPEND, MEMBERSUSPENDDAYS) VALUES ('serena@gmail.com', 'abc1234', 'Serena', 'Lee', 'Serena', 'F', '1988-01-01', 'sensitive', 'src\main\webapp\WEB-INF\img\member\member_default.png', '0910123456', 'Taipei Taiwan', 0, '30')

INSERT INTO ARTICLE (MEMBERID, ARTICLETYPE, ARTICLETITLE, ARTICLE, ARTICLETIME, ARTICLECOLLECT, ARTICLESHOW, ARTICLEREPORT) VALUES (5,'news','標題1','內文1','2016-06-22',5,1,0)
INSERT INTO ARTICLE (MEMBERID, ARTICLETYPE, ARTICLETITLE, ARTICLE, ARTICLETIME, ARTICLECOLLECT, ARTICLESHOW, ARTICLEREPORT) VALUES (1,'question','標題2','內文2','2016-04-02',0,1,0)
INSERT INTO ARTICLE (MEMBERID, ARTICLETYPE, ARTICLETITLE, ARTICLE, ARTICLETIME, ARTICLECOLLECT, ARTICLESHOW, ARTICLEREPORT) VALUES (10,'chat','標題3','內文3','2016-03-09',19,0,5)
INSERT INTO ARTICLE (MEMBERID, ARTICLETYPE, ARTICLETITLE, ARTICLE, ARTICLETIME, ARTICLECOLLECT, ARTICLESHOW, ARTICLEREPORT) VALUES (8,'chat','標題4','內文4','2016-03-05',2,1,2)
INSERT INTO ARTICLE (MEMBERID, ARTICLETYPE, ARTICLETITLE, ARTICLE, ARTICLETIME, ARTICLECOLLECT, ARTICLESHOW, ARTICLEREPORT) VALUES (5,'solicit','標題5','內文5','2016-03-01',5,0,6)

--INSERT INTO CATEGORY(NAME) VALUES ('category1')
--INSERT INTO CATEGORY(NAME) VALUES ('category2')
--INSERT INTO CATEGORY(NAME) VALUES ('category3')

--INSERT INTO BOOK(NAME, CATEGORYID) VALUES ('bookA', 1)
--INSERT INTO BOOK(NAME, CATEGORYID) VALUES ('bookB', 2)
--INSERT INTO BOOK(NAME, CATEGORYID) VALUES ('bookC', 3)

INSERT INTO PROINGRELIST(prodId,ingredId) values (1,1)
INSERT INTO PROINGRELIST(prodId,ingredId) values (1,2)
INSERT INTO PROINGRELIST(prodId,ingredId) values (1,3)
INSERT INTO PROINGRELIST(prodId,ingredId) values (1,4)